server:
  port: 8082
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  data:
    redis:
      port: 6379
      password: 221796
      host: 47.109.28.196
      database: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 221796
    url: jdbc:mysql://47.109.28.196:3306/online_education
  mail:
    host: smtp.163.com
    username: 13408180434@163.com
    password: PHcCAFxqUSwHquzd
    protocol: smtps
    port: 465
  rabbitmq:
    addresses: 47.109.28.196
    port: 5672
    username: ten
    password: 221796
  application:
    name: OE-course-service
  cloud:
    nacos:
      server-addr: 47.109.28.196:8848
    loadbalancer:
      retry:
        enabled: true
  mvc:
    static-path-pattern: /static/**
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      update-strategy: not_null
logging:
  level:
    root: info
    com.tenxi: debug
    org.springframework.web: debug
    org.springframework.security: debug
    com.alibaba.nacos: warn
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId}] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId}] %logger{36} - %msg%n"
  file:
    path: "logs/${spring.application.name}"
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: BASIC
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tHDUT9PTELhR3AHVnzW
    access-key-secret: Ni7qvQjwigVDsz7PZPjC9h3K6PUMFA
    bucket-name: online-education10
    folder: courses/
online:
  education:
    secret: XXssssjkewofokopweejfjfwwdlwdddhhhh
oe:
  elasticsearch:
    auto-create-index: true
    index-setting:
      shards: 1   #分片数量
      replicas: 1 #副本数量
  auth:
    include-paths:
      - "/users/login"
      - "/users/register"
      - "/users/ask-code"
      - "/category/tree"