server:
  port: 8085
spring:
  data:
    redis:
      port: 6379
      password: 221796
      host: 47.109.28.196
      database: 0
  mvc:
    static-path-pattern: /static/**
  cloud:
    nacos:
      discovery:
        server-addr: 47.109.28.196:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 221796
    url: jdbc:mysql://47.109.28.196:3306/online_education
  application:
    name: OE-progress-service
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      update-strategy: not_null
logging:
  level:
    org:
      root: info
      com.tenxi: debug
      org.springframework.web: debug
      org.springframework.security: debug
  file:
    path: "logs/${spring.application.name}"
online:
  education:
    secret: XXssssjkewofokopweejfjfwwdlwdddhhhh
oe:
  auth:
    include-paths:
      - "/users/login"
      - "/users/register"
      - "/users/ask-code"